// src/components/home/EventReview.vue
<template>
  <div ref="containerRef" class="review-container h-full relative overflow-hidden flex flex-col items-center justify-center px-16">
    <Background />

    <div class="relative z-10 w-full">
      <div class="text-center mb-12" data-reveal>
        <p class="text-sm tracking-widest mb-2 section-label">EVENT REVIEW</p>
        <h2 class="section-title text-5xl md:text-6xl font-bold">活動回顧</h2>
        <p class="mt-3 text-lg section-subtitle">我們一起走過的足跡</p>
      </div>

      <div v-if="events.length === 0" class="text-center" style="color: var(--color-text-muted);" data-reveal data-reveal-delay="200">
        目前沒有歷史活動
      </div>

      <div v-else class="timeline-wrapper" data-reveal data-reveal-delay="200">
        <div class="timeline-line"></div>
        <div class="timeline-track">
          <div
            v-for="(event, i) in reversedEvents"
            :key="event.id"
            class="timeline-item"
            :class="{ 'item-top': i % 2 === 0, 'item-bottom': i % 2 !== 0 }"
            data-reveal
            :data-reveal-delay="300 + i * 100"
            @click="openModal(event)"
          >
            <div class="timeline-dot"></div>
            <div class="timeline-card">
              <p class="timeline-date">{{ event.date }}</p>
              <h3 class="font-bold">{{ event.title }}</h3>
            </div>
          </div>
        </div>
      </div>
    </div>

    <EventModal :event="selectedEvent" :groups="groups" @close="closeModal" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import Background from '../common/Background.vue';
import EventModal from '../common/EventModal.vue';
import { useScrollReveal } from '../useScrollReveal';

interface EventItem {
  id: string;
  title: string;
  date: string;
  type: string;
  group: string;
  location?: string;
  description: string;
  content?: string;
  links?: { label: string; url: string }[];
  registration?: string;
}

const props = defineProps<{
  events: EventItem[];
  groups: { slug: string; name: string }[];
}>();

const reversedEvents = computed(() => [...props.events].reverse());
const { containerRef } = useScrollReveal();
const selectedEvent = ref<EventItem | null>(null);

const groupName = (slug: string) => {
  const g = props.groups.find(g => g.slug === slug);
  return g ? g.name : slug;
};

const openModal = (event: EventItem) => {
  selectedEvent.value = event;
};

const closeModal = () => {
  selectedEvent.value = null;
};
</script>

<style scoped>
.review-container {
  height: 100%;
  background: linear-gradient(to top, #030b23 0%, #063238 100%);
}

[data-reveal] {
  opacity: 0;
  transform: translateY(30px);
  transition: opacity 0.6s ease, transform 0.6s ease;
}

[data-reveal].revealed {
  opacity: 1;
  transform: translateY(0);
}

.section-title {
  position: relative;
  display: inline-block;
  padding-bottom: 0.75rem;
  background: linear-gradient(to top right, #3b82f6 0%, #34d399 100%);
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  filter:
    drop-shadow(0 0 12px rgba(59, 130, 246, 0.6))
    drop-shadow(0 0 25px rgba(52, 211, 153, 0.4))
    drop-shadow(2px 4px 0px rgba(0, 0, 0, 0.6));
}

.section-title::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 50%;
  transform: translateX(-50%);
  width: 60%;
  height: 2px;
  background: linear-gradient(90deg, transparent, #3b82f6, #06b6d4, transparent);
  filter: drop-shadow(0 0 6px #3b82f6);
}

.section-label {
  color: rgba(96, 165, 250, 0.8);
  text-shadow: 0 0 8px rgba(59, 130, 246, 0.4);
}

.section-subtitle {
  color: rgba(226, 232, 240, 0.85);
  text-shadow: 0 1px 3px rgba(0, 0, 0, 0.5);
}

.timeline-wrapper {
  position: relative;
  overflow-x: auto;
  padding: 4rem 1rem;
}

.timeline-line {
  position: absolute;
  top: 50%;
  left: 0;
  right: 0;
  height: 2px;
  background: linear-gradient(90deg, transparent, rgba(59, 130, 246, 0.4), rgba(59, 130, 246, 0.4), transparent);
}

.timeline-track {
  display: flex;
  gap: 4rem;
  position: relative;
  min-width: max-content;
  padding: 0 2rem;
}

.timeline-item {
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 180px;
  flex-shrink: 0;
  cursor: pointer;
  color: inherit;
  height: 200px;
}

.timeline-dot {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: #3b82f6;
  box-shadow: 0 0 10px rgba(59, 130, 246, 0.7);
  transition: all 0.3s ease;
  z-index: 1;
}

.timeline-item:hover .timeline-dot {
  transform: translate(-50%, -50%) scale(1.4);
  box-shadow: 0 0 20px rgba(59, 130, 246, 0.9);
}

.timeline-card {
  position: absolute;
  left: 0;
  right: 0;
  border-radius: 0.5rem;
  border: 2px solid rgba(255, 255, 255, 0.1);
  background: rgba(10, 14, 26, 0.01);
  backdrop-filter: blur(8px);
  padding: 1rem;
  text-align: center;
  transition: all 0.3s ease;
}

.item-top .timeline-card {
  top: 0;
}

.item-bottom .timeline-card {
  bottom: 0;
}

.timeline-item:hover .timeline-card {
  border-color: rgba(59, 130, 246, 0.4);
  background: rgba(10, 14, 26, 0.3);
  box-shadow: 0 0 15px rgba(59, 130, 246, 0.15);
}

.timeline-date {
  font-size: 0.75rem;
  color: var(--color-text-muted);
  margin-bottom: 0.25rem;
}
</style>

// src/components/home/EventReview.tsx
import { useMemo, useState } from 'react';
import type { EventItem, GroupRef, ShowcaseItem } from '../../types/content';
import Background from '../common/Background';
import EventModal from '../common/EventModal';
import { useScrollReveal } from '../../hooks/useScrollReveal';
import styles from './EventReview.module.css';

interface Props {
  events: EventItem[];
  groups: GroupRef[];
  showcaseItems: ShowcaseItem[];
}

export default function EventReview({ events, groups, showcaseItems }: Props) {
  const reversedEvents = useMemo(() => [...events].reverse(), [events]);
  const { containerRef } = useScrollReveal();
  const [selectedEvent, setSelectedEvent] = useState<EventItem | null>(null);

  return (
    <div
      ref={containerRef}
      className={`${styles['review-container']} h-full relative overflow-hidden flex flex-col items-center justify-center px-16`}
    >
      <Background />

      <div className="relative z-10 w-full">
        <div className="text-center mb-12" data-reveal="">
          <p className={`text-sm tracking-widest mb-2 ${styles['section-label']}`}>EVENT REVIEW</p>
          <h2 className={`${styles['section-title']} text-5xl md:text-6xl font-bold`}>活動回顧</h2>
          <p className={`mt-3 text-lg ${styles['section-subtitle']}`}>我們一起走過的足跡</p>
        </div>

        {events.length === 0 ? (
          <div
            className="text-center"
            style={{ color: 'var(--color-text-muted)' }}
            data-reveal=""
            data-reveal-delay="200"
          >
            目前沒有歷史活動
          </div>
        ) : (
          <div className={styles['timeline-wrapper']} data-reveal="" data-reveal-delay="200">
            <div className={styles['timeline-line']}></div>
            <div className={styles['timeline-track']}>
              {reversedEvents.map((event, i) => (
                <div
                  key={event.id}
                  className={`${styles['timeline-item']} ${i % 2 === 0 ? styles['item-top'] : styles['item-bottom']}`}
                  data-reveal=""
                  data-reveal-delay={300 + i * 100}
                  onClick={() => setSelectedEvent(event)}
                >
                  <div className={styles['timeline-dot']}></div>
                  <div className={styles['timeline-card']}>
                    <p className={styles['timeline-date']}>{event.date}</p>
                    <h3 className="font-bold">{event.title}</h3>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      <EventModal
        event={selectedEvent}
        groups={groups}
        showcaseItems={showcaseItems}
        onClose={() => setSelectedEvent(null)}
      />
    </div>
  );
}
