// src/components/home/HeroSection.tsx
import { useEffect, useRef, useState } from 'react';
import figlet from 'figlet';
import standard from 'figlet/importable-fonts/Standard.js';
import Background from '../common/Background';
import { useScrollReveal } from '../../hooks/useScrollReveal';
import styles from './HeroSection.module.css';

// 模組層級：SSR 也會執行，但只註冊字型，不碰 window
figlet.parseFont('Standard', standard);

export default function HeroSection() {
  const { containerRef } = useScrollReveal();

  const [isHovered, setIsHovered] = useState(false);
  // SSR 與 hydrate 時為空字串，掛載後才填入，避免伺服器與瀏覽器輸出不一致
  const [asciiArt, setAsciiArt] = useState('');
  const [inputText, setInputText] = useState('');
  const composing = useRef(false);

  const renderAscii = (text: string) => {
    figlet.text(text, { font: 'Standard' }, (err, result) => {
      if (!err && result) {
        setAsciiArt(result);
      }
    });
  };

  const updateAscii = (value: string) => {
    const text = value.trim() || 'NCNU ACM';
    renderAscii(text);
  };

  useEffect(() => {
    renderAscii('NCNU ACM');
  }, []);

  // 輸入法組字期間（compositionstart → compositionend）不更新 inputText，等組字結束才用最終文字更新並重畫 ASCII，
  // 否則注音／拼音組字中的中間字母會被拿去畫 ASCII，且組字第一個字時 placeholder 會提早消失。
  // 因此 <input> 維持非受控（defaultValue），只由這個函式把值單向寫進 state。
  const commit = (value: string) => {
    setInputText(value);
    updateAscii(value);
  };

  return (
    <div
      ref={containerRef}
      className={`${styles['hero-container']} flex flex-col h-full relative overflow-hidden`}
    >
      <Background />
      <div className="flex flex-col items-center justify-center flex-1 relative z-10 text-center px-8">
        <div className={styles['title-wrapper']} data-reveal="">
          <pre className={styles['ascii-bg']}>{asciiArt}</pre>
          <h1
            className={`text-7xl md:text-8xl lg:text-9xl font-bold mb-4 tracking-tight relative z-10 ${styles['hero-title']}`}
          >
            NCNU ACM
          </h1>
        </div>

        <div className="mb-6" data-reveal="" data-reveal-delay="150">
          <p className={`text-3xl md:text-4xl lg:text-5xl ${styles['gradient-text']} font-bold`}>
            程式設計 × 系統開發 × 創意實踐
          </p>
        </div>

        <div className="flex flex-wrap gap-4 justify-center mt-6" data-reveal="" data-reveal-delay="300">
          <a
            href="/join"
            className={`inline-block px-8 py-4 rounded-full font-medium transition-all hover:scale-105 ${styles['glow-button']}`}
          >
            加入我們 →
          </a>
          <a
            href="/events"
            className={`inline-block px-8 py-4 rounded-full font-medium transition-all hover:scale-105 ${styles['outline-button']}`}
          >
            活動公告
          </a>
          <a
            href="/about/introduction"
            className={`inline-block px-8 py-4 rounded-full font-medium transition-all hover:scale-105 ${styles['outline-button']}`}
          >
            關於我們
          </a>
        </div>

        <div
          className={`${styles['terminal-input-bar']} mt-8`}
          data-reveal=""
          data-reveal-delay="450"
          onMouseEnter={() => setIsHovered(true)}
          onMouseLeave={() => setIsHovered(false)}
        >
          {!inputText && (
            <span className={`${styles['placeholder-text']}${isHovered ? ` ${styles.active}` : ''}`}>NCNU ACM</span>
          )}
          <input
            type="text"
            className={`${styles['terminal-input']}${isHovered ? ` ${styles.active}` : ''}`}
            defaultValue=""
            maxLength={12}
            onInput={(e) => {
              if (composing.current) return;
              commit(e.currentTarget.value);
            }}
            onCompositionStart={() => {
              composing.current = true;
            }}
            onCompositionEnd={(e) => {
              composing.current = false;
              commit(e.currentTarget.value);
            }}
          />
          <span className={`${styles.cursor}${isHovered ? ` ${styles.active}` : ''}`}>_</span>
        </div>
      </div>
    </div>
  );
}

// src/components/home/HeroSection.vue
<template>
  <div ref="containerRef" class="hero-container flex flex-col h-full relative overflow-hidden">
    <Background />
    <div class="flex flex-col items-center justify-center flex-1 relative z-10 text-center px-8">
      <div class="title-wrapper" data-reveal>
        <pre class="ascii-bg">{{ asciiArt }}</pre>
        <h1 class="text-7xl md:text-8xl lg:text-9xl font-bold mb-4 tracking-tight relative z-10 hero-title">
          NCNU ACM
        </h1>
      </div>

      <div class="mb-6" data-reveal data-reveal-delay="150">
        <p class="text-3xl md:text-4xl lg:text-5xl gradient-text font-bold">
          程式設計 × 系統開發 × 創意實踐
        </p>
      </div>

      <div class="flex flex-wrap gap-4 justify-center mt-6" data-reveal data-reveal-delay="300">
        <a href="/join" class="inline-block px-8 py-4 rounded-full font-medium transition-all hover:scale-105 glow-button">
          加入我們 →
        </a>
        <a href="/events" class="inline-block px-8 py-4 rounded-full font-medium transition-all hover:scale-105 outline-button">
          活動公告
        </a>
        <a href="/about/introduction" class="inline-block px-8 py-4 rounded-full font-medium transition-all hover:scale-105 outline-button">
          關於我們
        </a>
      </div>

      <div class="terminal-input-bar mt-8" data-reveal data-reveal-delay="450"
          @mouseenter="isHovered = true"
          @mouseleave="isHovered = false">
          <span v-if="!inputText" class="placeholder-text" :class="{ active: isHovered }">NCNU ACM</span>
          <input
            v-model="inputText"
            @input="updateAscii"
            type="text"
            class="terminal-input"
            :class="{ active: isHovered }"
            maxlength="12"
          />
        <span class="cursor" :class="{ active: isHovered }">_</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import figlet from 'figlet';
import standard from 'figlet/importable-fonts/Standard.js';
import Background from '../common/Background.vue';
import { useScrollReveal } from '../../composables/useScrollReveal.ts';

const { containerRef } = useScrollReveal();

const isHovered = ref(false);
figlet.parseFont('Standard', standard);

const asciiArt = ref('');
const inputText = ref('');

const renderAscii = (text: string) => {
  figlet.text(text, { font: 'Standard' }, (err, result) => {
    if (!err && result) {
      asciiArt.value = result;
    }
  });
};

const updateAscii = () => {
  const text = inputText.value.trim() || 'NCNU ACM';
  renderAscii(text);
};

onMounted(() => {
  renderAscii('NCNU ACM');
});
</script>

<style scoped>
.hero-container {
  height: 100%;
  background: linear-gradient(to top, #030b23 0%, #063238 100%);
}

[data-reveal] {
  opacity: 0;
  transform: translateY(30px);
  transition: opacity 0.6s ease, transform 0.6s ease;
}

[data-reveal].revealed {
  opacity: 1;
  transform: translateY(0);
}

.title-wrapper {
  position: relative;
  display: inline-block;
}

.hero-title {
  background: linear-gradient(to top right, #3b82f6 0%, #34d399 100%);
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  -webkit-text-stroke: 1px rgba(255, 255, 255, 0.5);
  filter: 
    drop-shadow(0 0 12px rgba(59, 130, 246, 0.6))
    drop-shadow(0 0 25px rgba(52, 211, 153, 0.4))
    drop-shadow(3px 6px 0px rgba(0, 0, 0, 1));
}

.ascii-bg {
  position: absolute;
  bottom: 0;
  left: 50%;
  transform: translate(-51.7%, 10%);
  font-family: monospace;
  font-size: clamp(20px, 3vw, 36px);
  color: rgba(59, 130, 246, 0.45);
  white-space: pre;
  overflow: hidden;
  pointer-events: none;
  line-height: 1.2;
  z-index: 0;
  filter: drop-shadow(0 0 8px rgba(59, 130, 246, 0.5));
}

.gradient-text {
  position: relative;
  display: inline-block;
  background: linear-gradient(135deg, #a78bfa 0%, #34d399 100%);
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  padding-bottom: 0.5rem;
}

.gradient-text::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 2px;
  background: linear-gradient(90deg, transparent, #a78bfa 20%, #34d399 80%, transparent);
}

.glow-button {
  background: linear-gradient(135deg, #3b82f6 0%, #06b6d4 100%);
  color: white;
  box-shadow: 0 0 20px rgba(59, 130, 246, 0.5);
}

.glow-button:hover {
  box-shadow: 0 0 30px rgba(59, 130, 246, 0.7);
}

.outline-button {
  background: transparent;
  color: white;
  border: 1px solid rgba(59, 130, 246, 0.6);
  box-shadow: 0 0 10px rgba(59, 130, 246, 0.2);
}

.outline-button:hover {
  border-color: #3b82f6;
  box-shadow: 0 0 20px rgba(59, 130, 246, 0.4);
}

.terminal-input-bar {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.5rem;
  border: 1px solid rgba(59, 130, 246, 0.2);
  border-radius: 9999px;
  background: rgba(10, 14, 26, 0.3);
  font-family: monospace;
  width: 100%;
  max-width: 400px;
  backdrop-filter: blur(4px);
  transition: all 0.3s ease;
}

.terminal-input-bar:hover {
  background: rgba(10, 14, 26, 0.9);
  border-color: rgba(59, 130, 246, 0.6);
  box-shadow: 0 0 20px rgba(59, 130, 246, 0.2);
}

.terminal-input {
  background: transparent;
  border: none;
  outline: none;
  color: rgba(226, 232, 240, 0.3);
  font-family: monospace;
  font-size: 1rem;
  flex: 1;
  transition: color 0.3s ease;
}

.prompt {
  color: rgba(59, 130, 246, 0.3);
  font-size: 1rem;
  transition: color 0.3s ease;
}

.cursor {
  color: rgba(59, 130, 246, 0.3);
  animation: blink 1s step-end infinite;
  transition: color 0.3s ease;
}

.terminal-input.active {
  color: rgba(226, 232, 240, 1);
}

.prompt.active {
  color: rgba(59, 130, 246, 1);
}

.cursor.active {
  color: rgba(59, 130, 246, 1);
}

.placeholder-text {
  position: absolute;
  color: rgba(226, 232, 240, 0.3);
  font-family: monospace;
  font-size: 1rem;
  pointer-events: none;
  transition: color 0.3s ease;
}

.placeholder-text.active {
  color: rgba(226, 232, 240, 0.6);
}

@keyframes blink {
  0%, 100% { opacity: 1; }
  50% { opacity: 0; }
}
</style>
