// src/components/common/EventModal.tsx
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import type { EventItem, GroupRef, ShowcaseItem } from '../../types/content';
import styles from './EventModal.module.css';

interface Props {
  event: EventItem | null;
  groups: GroupRef[];
  showcaseItems: ShowcaseItem[];
  onClose: () => void;
}

type ViewMode = 'announcement' | 'recap';

export default function EventModal({ event, groups, showcaseItems, onClose }: Props) {
  // Vue 的 watch(() => props.event) 不是 immediate：掛載時不碰 body，只有 event 之後變動才鎖／解鎖。
  // 用 layout effect 讓它在繪製前執行，對應 watch 預設的 flush: 'pre'。
  const mounted = useRef(false);
  useLayoutEffect(() => {
    if (!mounted.current) {
      mounted.current = true;
      return;
    }
    document.body.style.overflow = event ? 'hidden' : '';
  }, [event]);

  // 卸載時一律設成 ''（不是還原先前的值）
  useEffect(() => {
    return () => {
      document.body.style.overflow = '';
    };
  }, []);

  if (!event) return null;

  // key 讓 viewMode 在每次開啟（或直接換成另一筆）時重置為 'announcement'，
  // 不必用 effect 重設，也就不會在開啟的第一個 frame 閃現上次的分頁
  return (
    <EventModalContent
      key={event.id}
      event={event}
      groups={groups}
      showcaseItems={showcaseItems}
      onClose={onClose}
    />
  );
}

function EventModalContent({
  event,
  groups,
  showcaseItems,
  onClose,
}: Props & { event: EventItem }) {
  const [viewMode, setViewMode] = useState<ViewMode>('announcement');

  const relatedShowcase = showcaseItems.find((s) => s.related_event === event.id) || null;

  const groupName = (slug: string) => {
    const g = groups.find((g) => g.slug === slug);
    return g ? g.name : slug;
  };

  return (
    <div
      className={styles['modal-overlay']}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      {/* index.astro 的 wheel 攔截靠 closest('.modal')，所以要保留字面 class */}
      <div className={`modal ${styles.modal}`}>
        <button className={styles['modal-close']} onClick={onClose}>
          ×
        </button>

        {relatedShowcase && (
          <div className={styles['view-toggle']}>
            <button
              className={`${styles['toggle-btn']}${viewMode === 'announcement' ? ` ${styles.active}` : ''}`}
              onClick={() => setViewMode('announcement')}
            >
              活動公告
            </button>
            <button
              className={`${styles['toggle-btn']}${viewMode === 'recap' ? ` ${styles.active}` : ''}`}
              onClick={() => setViewMode('recap')}
            >
              活動回顧
            </button>
          </div>
        )}

        {viewMode === 'announcement' ? (
          <div>
            <div className={styles['modal-tags']}>
              {event.isAnnouncement ? (
                <span className={`${styles.tag} ${styles['announcement-tag']}`}>通知</span>
              ) : (
                <span className={styles.tag}>{event.type}</span>
              )}
              {!event.isAnnouncement && event.group && (
                <span className={`${styles.tag} ${styles['tag-group']}`}>{groupName(event.group)}</span>
              )}
            </div>
            <h2 className={styles['modal-title']}>{event.title}</h2>
            <div className={styles['modal-meta']}>
              {!event.isAnnouncement ? (
                <span>{`活動日期: ${event.date}`}</span>
              ) : (
                <span>{`發布日期: ${event.date}`}</span>
              )}
              {event.location && <span>{`活動地點: ${event.location}`}</span>}
            </div>

            {event.content && <p className={styles['modal-description']}>{event.content}</p>}

            {event.links && event.links.length > 0 && (
              <div className={styles['modal-links']}>
                {event.links.map((link) => (
                  <a
                    key={link.label}
                    href={link.url}
                    target="_blank"
                    className={styles['modal-link-item']}
                  >
                    {`🔗 ${link.label}`}
                  </a>
                ))}
              </div>
            )}

            {event.registration && (
              <a href={event.registration} target="_blank" className={styles['modal-register-btn']}>
                立即報名 →
              </a>
            )}
          </div>
        ) : (
          relatedShowcase && (
            <div>
              <div className={styles['modal-tags']}>
                {!event.isAnnouncement && <span className={styles.tag}>{event.type}</span>}
                {event.isAnnouncement && (
                  <span className={`${styles.tag} ${styles['announcement-tag']}`}>通知</span>
                )}
                {!event.isAnnouncement && event.group && (
                  <span className={`${styles.tag} ${styles['tag-group']}`}>{groupName(event.group)}</span>
                )}
              </div>
              <h2 className={styles['modal-title']}>{relatedShowcase.title}</h2>
              <div className={styles['modal-meta']}>
                <span>{`📅 ${relatedShowcase.date}`}</span>
              </div>

              {relatedShowcase.cover_image && (
                <img src={relatedShowcase.cover_image} className={styles['cover-image']} />
              )}

              <p className={styles['modal-description']}>{relatedShowcase.description}</p>

              {relatedShowcase.gallery && relatedShowcase.gallery.length > 0 && (
                <div className={styles['gallery-grid']}>
                  {relatedShowcase.gallery.map((img, i) => (
                    <img key={i} src={img} className={styles['gallery-image']} />
                  ))}
                </div>
              )}

              {relatedShowcase.links && relatedShowcase.links.length > 0 && (
                <div className={styles['modal-links']}>
                  {relatedShowcase.links.map((link) => (
                    <a
                      key={link.label}
                      href={link.url}
                      target="_blank"
                      className={styles['modal-link-item']}
                    >
                      {`🔗 ${link.label}`}
                    </a>
                  ))}
                </div>
              )}
            </div>
          )
        )}
      </div>
    </div>
  );
}

// src/components/common/EventModal.vue
<template>
  <div v-if="event" class="modal-overlay" @click.self="$emit('close')">
    <div class="modal">
      <button class="modal-close" @click="$emit('close')">×</button>

      <div v-if="relatedShowcase" class="view-toggle">
        <button
          class="toggle-btn"
          :class="{ active: viewMode === 'announcement' }"
          @click="viewMode = 'announcement'"
        >
          活動公告
        </button>
        <button
          class="toggle-btn"
          :class="{ active: viewMode === 'recap' }"
          @click="viewMode = 'recap'"
        >
          活動回顧
        </button>
      </div>

      <div v-if="viewMode === 'announcement'">
        <div class="modal-tags">
          <span v-if="event.isAnnouncement" class="tag announcement-tag">通知</span>
          <span v-else class="tag">{{ event.type }}</span>
          <span v-if="!event.isAnnouncement && event.group" class="tag tag-group">{{ groupName(event.group) }}</span>
        </div>
        <h2 class="modal-title">{{ event.title }}</h2>
        <div class="modal-meta">
          <span v-if="!event.isAnnouncement">活動日期: {{ event.date }}</span>
          <span v-else>發布日期: {{ event.date }}</span>
          <span v-if="event.location">活動地點: {{ event.location }}</span>
        </div>

        <p v-if="event.content" class="modal-description">{{ event.content }}</p>

        <div v-if="event.links && event.links.length" class="modal-links">
          <a
            v-for="link in event.links"
            :key="link.label"
            :href="link.url"
            target="_blank"
            class="modal-link-item"
          >
            🔗 {{ link.label }}
          </a>
        </div>

        <a
          v-if="event.registration"
          :href="event.registration"
          target="_blank"
          class="modal-register-btn"
        >
          立即報名 →
        </a>
      </div>

      <div v-else-if="relatedShowcase">
        <div class="modal-tags">
          <span v-if="!event.isAnnouncement" class="tag">{{ event.type }}</span>
          <span v-if="event.isAnnouncement" class="tag announcement-tag">通知</span>
          <span v-if="!event.isAnnouncement && event.group" class="tag tag-group">{{ groupName(event.group) }}</span>
        </div>
        <h2 class="modal-title">{{ relatedShowcase.title }}</h2>
        <div class="modal-meta">
          <span>📅 {{ relatedShowcase.date }}</span>
        </div>

        <img v-if="relatedShowcase.cover_image" :src="relatedShowcase.cover_image" class="cover-image" />

        <p class="modal-description">{{ relatedShowcase.description }}</p>

        <div v-if="relatedShowcase.gallery && relatedShowcase.gallery.length" class="gallery-grid">
          <img
            v-for="(img, i) in relatedShowcase.gallery"
            :key="i"
            :src="img"
            class="gallery-image"
          />
        </div>

        <div v-if="relatedShowcase.links && relatedShowcase.links.length" class="modal-links">
          <a
            v-for="link in relatedShowcase.links"
            :key="link.label"
            :href="link.url"
            target="_blank"
            class="modal-link-item"
          >
            🔗 {{ link.label }}
          </a>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onUnmounted } from 'vue';

interface EventItem {
  id: string;
  title: string;
  date: string;
  type: string;
  group: string;
  location?: string;
  description: string;
  content?: string;
  links?: { label: string; url: string }[];
  registration?: string;
  isAnnouncement?: boolean;
}

interface ShowcaseItem {
  id: string;
  title: string;
  group: string;
  date: string;
  description: string;
  related_event?: string;
  cover_image?: string;
  gallery?: string[];
  tags?: string[];
  links?: { label: string; url: string }[];
}

const props = defineProps<{
  event: EventItem | null;
  groups: { slug: string; name: string }[];
  showcaseItems: ShowcaseItem[];
}>();

defineEmits<{
  close: [];
}>();

const viewMode = ref<'announcement' | 'recap'>('announcement');

const relatedShowcase = computed(() => {
  if (!props.event) return null;
  return props.showcaseItems.find(s => s.related_event === props.event!.id) || null;
});

watch(() => props.event, (newEvent) => {
  viewMode.value = 'announcement';
  if (newEvent) {
    document.body.style.overflow = 'hidden';
  } else {
    document.body.style.overflow = '';
  }
});

onUnmounted(() => {
  document.body.style.overflow = '';
});

const groupName = (slug: string) => {
  const g = props.groups.find(g => g.slug === slug);
  return g ? g.name : slug;
};
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.7);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 100;
  padding: 2rem;
}

.modal {
  position: relative;
  background: #0f1729;
  border: 1px solid rgba(59, 130, 246, 0.3);
  border-radius: 1rem;
  padding: 2.5rem;
  width: 100%;
  max-width: 780px;
  max-height: 80vh;
  overflow-y: auto;
  box-shadow: 0 0 40px rgba(59, 130, 246, 0.2);
  scrollbar-width: thin;
  scrollbar-color: rgba(59, 130, 246, 0.4) rgba(255, 255, 255, 0.05);
}

.modal::-webkit-scrollbar {
  width: 6px;
}

.modal::-webkit-scrollbar-track {
  background: rgba(255, 255, 255, 0.05);
  border-radius: 3px;
}

.modal::-webkit-scrollbar-thumb {
  background: rgba(59, 130, 246, 0.4);
  border-radius: 3px;
}

.modal::-webkit-scrollbar-thumb:hover {
  background: rgba(59, 130, 246, 0.6);
}

.modal-close {
  position: absolute;
  top: 1rem;
  right: 1.25rem;
  background: none;
  border: none;
  color: rgba(226, 232, 240, 0.6);
  font-size: 1.5rem;
  cursor: pointer;
}

.modal-close:hover {
  color: white;
}

.view-toggle {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
  padding-bottom: 1rem;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.toggle-btn {
  flex: 1;
  padding: 0.6rem 1rem;
  border-radius: 0.5rem;
  border: 1px solid rgba(255, 255, 255, 0.1);
  background: rgba(255, 255, 255, 0.03);
  color: rgba(226, 232, 240, 0.6);
  font-size: 0.9rem;
  cursor: pointer;
  transition: all 0.2s ease;
}

.toggle-btn:hover {
  background: rgba(255, 255, 255, 0.06);
}

.toggle-btn.active {
  background: rgba(59, 130, 246, 0.2);
  border-color: rgba(59, 130, 246, 0.5);
  color: #60a5fa;
}

.modal-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 1rem;
}

.tag {
  font-size: 0.75rem;
  padding: 0.25rem 0.75rem;
  border-radius: 9999px;
  background: rgba(59, 130, 246, 0.15);
  color: #60a5fa;
  border: 1px solid rgba(59, 130, 246, 0.3);
}

.tag-group {
  background: rgba(6, 182, 212, 0.15);
  color: #22d3ee;
  border-color: rgba(6, 182, 212, 0.3);
}

.announcement-tag {
  background: rgba(251, 191, 36, 0.15);
  color: #fbbf24;
  border-color: rgba(251, 191, 36, 0.3);
}

.modal-title {
  font-size: 1.75rem;
  font-weight: bold;
  color: white;
  margin-bottom: 1rem;
}

.modal-meta {
  display: flex;
  gap: 1.5rem;
  font-size: 0.95rem;
  color: rgba(226, 232, 240, 0.6);
  margin-bottom: 1.5rem;
}

.modal-description {
  color: rgba(226, 232, 240, 0.85);
  line-height: 1.8;
  margin-bottom: 1.5rem;
  white-space: pre-line;
}

.cover-image {
  width: 100%;
  border-radius: 0.75rem;
  margin-bottom: 1.5rem;
  object-fit: cover;
}

.gallery-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 0.75rem;
  margin-bottom: 1.5rem;
}

.gallery-image {
  width: 100%;
  aspect-ratio: 1 / 1;
  object-fit: cover;
  border-radius: 0.5rem;
}

.modal-links {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
}

.modal-link-item {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.6rem 1rem;
  border-radius: 0.5rem;
  border: 1px solid rgba(59, 130, 246, 0.3);
  background: rgba(59, 130, 246, 0.08);
  color: #60a5fa;
  text-decoration: none;
  font-size: 0.9rem;
  transition: all 0.2s ease;
}

.modal-link-item:hover {
  background: rgba(59, 130, 246, 0.18);
  border-color: rgba(59, 130, 246, 0.5);
}

.modal-register-btn {
  display: inline-block;
  padding: 0.75rem 1.5rem;
  border-radius: 9999px;
  background: linear-gradient(135deg, #3b82f6 0%, #06b6d4 100%);
  color: white;
  text-decoration: none;
  font-weight: 500;
  box-shadow: 0 0 20px rgba(59, 130, 246, 0.4);
}
</style>
