// src/components/common/ShowcaseModal.vue
<template>
  <div v-if="showcase" class="modal-overlay" @click.self="$emit('close')">
    <div class="modal">
      <button class="modal-close" @click="$emit('close')">×</button>

      <div v-if="relatedEvent" class="view-toggle">
        <button
          class="toggle-btn"
          :class="{ active: viewMode === 'showcase' }"
          @click="viewMode = 'showcase'"
        >
          活動回顧
        </button>
        <button
          class="toggle-btn"
          :class="{ active: viewMode === 'announcement' }"
          @click="viewMode = 'announcement'"
        >
          活動公告
        </button>
      </div>

      <div v-if="viewMode === 'showcase'">
        <div class="modal-tags">
          <span class="tag tag-group">{{ groupName(showcase.group) }}</span>
          <span v-for="tag in showcase.tags" :key="tag" class="tag">{{ tag }}</span>
        </div>
        <h2 class="modal-title">{{ showcase.title }}</h2>
        <div class="modal-meta">
          <span>📅 {{ showcase.date }}</span>
        </div>

        <img v-if="showcase.cover_image" :src="showcase.cover_image" class="cover-image" :alt="showcase.title" />

        <p class="modal-description">{{ showcase.description }}</p>

        <div v-if="showcase.gallery && showcase.gallery.length" class="gallery-grid">
          <img
            v-for="(img, i) in showcase.gallery"
            :key="i"
            :src="img"
            class="gallery-image"
            @click="openLightbox(i)"
          />
        </div>

        <div v-if="showcase.links && showcase.links.length" class="modal-links">
          <a
            v-for="link in showcase.links"
            :key="link.label"
            :href="link.url"
            target="_blank"
            class="modal-link-item"
          >
            🔗 {{ link.label }}
          </a>
        </div>
      </div>

      <div v-else-if="relatedEvent">
        <div class="modal-tags">
          <span class="tag">{{ relatedEvent.type }}</span>
          <span class="tag tag-group">{{ groupName(relatedEvent.group) }}</span>
        </div>
        <h2 class="modal-title">{{ relatedEvent.title }}</h2>
        <div class="modal-meta">
          <span>📅 {{ relatedEvent.date }}</span>
          <span v-if="relatedEvent.location">📍 {{ relatedEvent.location }}</span>
        </div>

        <p v-if="relatedEvent.content" class="modal-description">{{ relatedEvent.content }}</p>

        <div v-if="relatedEvent.links && relatedEvent.links.length" class="modal-links">
          <a
            v-for="link in relatedEvent.links"
            :key="link.label"
            :href="link.url"
            target="_blank"
            class="modal-link-item"
          >
            🔗 {{ link.label }}
          </a>
        </div>

        <a
          v-if="relatedEvent.registration"
          :href="relatedEvent.registration"
          target="_blank"
          class="modal-register-btn"
        >
          立即報名 →
        </a>
      </div>
    </div>

    <div v-if="lightboxIndex !== null" class="lightbox" @click="closeLightbox">
      <button class="lightbox-close" @click.stop="closeLightbox">×</button>
      <button class="lightbox-prev" @click.stop="lightboxPrev">‹</button>
      <img :src="showcase.gallery![lightboxIndex]" class="lightbox-img" @click.stop />
      <button class="lightbox-next" @click.stop="lightboxNext">›</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';

interface ShowcaseItem {
  id: string;
  title: string;
  group: string;
  date: string;
  description: string;
  related_event?: string;
  cover_image?: string;
  gallery?: string[];
  tags?: string[];
  links?: { label: string; url: string }[];
}

interface EventItem {
  id: string;
  title: string;
  date: string;
  type: string;
  group: string;
  location?: string;
  description: string;
  content?: string;
  links?: { label: string; url: string }[];
  registration?: string;
}

const props = defineProps<{
  showcase: ShowcaseItem | null;
  events: EventItem[];
  groups: { slug: string; name: string }[];
}>();

defineEmits<{ close: [] }>();

const viewMode = ref<'showcase' | 'announcement'>('showcase');
const lightboxIndex = ref<number | null>(null);

const relatedEvent = computed(() => {
  if (!props.showcase?.related_event) return null;
  return props.events.find(e => e.id === props.showcase!.related_event) || null;
});

watch(() => props.showcase, () => {
  viewMode.value = 'showcase';
  lightboxIndex.value = null;
});

const groupName = (slug: string) => {
  const g = props.groups.find(g => g.slug === slug);
  return g ? g.name : slug;
};

const openLightbox = (index: number) => {
  lightboxIndex.value = index;
};

const closeLightbox = () => {
  lightboxIndex.value = null;
};

const lightboxPrev = () => {
  if (lightboxIndex.value === null || !props.showcase?.gallery) return;
  lightboxIndex.value = (lightboxIndex.value - 1 + props.showcase.gallery.length) % props.showcase.gallery.length;
};

const lightboxNext = () => {
  if (lightboxIndex.value === null || !props.showcase?.gallery) return;
  lightboxIndex.value = (lightboxIndex.value + 1) % props.showcase.gallery.length;
};
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.7);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 100;
  padding: 2rem;
}

.modal {
  position: relative;
  background: #0f1729;
  border: 1px solid rgba(59, 130, 246, 0.3);
  border-radius: 1rem;
  padding: 2.5rem;
  width: 100%;
  max-width: 600px;
  max-height: 85vh;
  overflow-y: auto;
  box-shadow: 0 0 40px rgba(59, 130, 246, 0.2);
  scrollbar-width: thin;
  scrollbar-color: rgba(59, 130, 246, 0.4) rgba(255, 255, 255, 0.05);
}

.modal::-webkit-scrollbar { width: 6px; }
.modal::-webkit-scrollbar-track { background: rgba(255, 255, 255, 0.05); border-radius: 3px; }
.modal::-webkit-scrollbar-thumb { background: rgba(59, 130, 246, 0.4); border-radius: 3px; }
.modal::-webkit-scrollbar-thumb:hover { background: rgba(59, 130, 246, 0.6); }

.modal-close {
  position: absolute;
  top: 1rem;
  right: 1.25rem;
  background: none;
  border: none;
  color: rgba(226, 232, 240, 0.6);
  font-size: 1.5rem;
  cursor: pointer;
}

.modal-close:hover { color: white; }

.view-toggle {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
  padding-bottom: 1rem;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.toggle-btn {
  flex: 1;
  padding: 0.6rem 1rem;
  border-radius: 0.5rem;
  border: 1px solid rgba(255, 255, 255, 0.1);
  background: rgba(255, 255, 255, 0.03);
  color: rgba(226, 232, 240, 0.6);
  font-size: 0.9rem;
  cursor: pointer;
  transition: all 0.2s ease;
}

.toggle-btn:hover { background: rgba(255, 255, 255, 0.06); }

.toggle-btn.active {
  background: rgba(59, 130, 246, 0.2);
  border-color: rgba(59, 130, 246, 0.5);
  color: #60a5fa;
}

.modal-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 1rem;
}

.tag {
  font-size: 0.75rem;
  padding: 0.25rem 0.75rem;
  border-radius: 9999px;
  background: rgba(59, 130, 246, 0.15);
  color: #60a5fa;
  border: 1px solid rgba(59, 130, 246, 0.3);
}

.tag-group {
  background: rgba(6, 182, 212, 0.15);
  color: #22d3ee;
  border-color: rgba(6, 182, 212, 0.3);
}

.modal-title {
  font-size: 1.75rem;
  font-weight: bold;
  color: white;
  margin-bottom: 1rem;
}

.modal-meta {
  display: flex;
  gap: 1.5rem;
  font-size: 0.95rem;
  color: rgba(226, 232, 240, 0.6);
  margin-bottom: 1.5rem;
}

.cover-image {
  width: 100%;
  border-radius: 0.75rem;
  margin-bottom: 1.5rem;
  object-fit: cover;
}

.modal-description {
  color: rgba(226, 232, 240, 0.85);
  line-height: 1.8;
  margin-bottom: 1.5rem;
  white-space: pre-line;
}

.gallery-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 0.5rem;
  margin-bottom: 1.5rem;
}

.gallery-image {
  width: 100%;
  aspect-ratio: 1 / 1;
  object-fit: cover;
  border-radius: 0.5rem;
  cursor: pointer;
  transition: opacity 0.2s ease;
}

.gallery-image:hover { opacity: 0.85; }

.modal-links {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
}

.modal-link-item {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.6rem 1rem;
  border-radius: 0.5rem;
  border: 1px solid rgba(59, 130, 246, 0.3);
  background: rgba(59, 130, 246, 0.08);
  color: #60a5fa;
  text-decoration: none;
  font-size: 0.9rem;
  transition: all 0.2s ease;
}

.modal-link-item:hover {
  background: rgba(59, 130, 246, 0.18);
  border-color: rgba(59, 130, 246, 0.5);
}

.modal-register-btn {
  display: inline-block;
  padding: 0.75rem 1.5rem;
  border-radius: 9999px;
  background: linear-gradient(135deg, #3b82f6 0%, #06b6d4 100%);
  color: white;
  text-decoration: none;
  font-weight: 500;
  box-shadow: 0 0 20px rgba(59, 130, 246, 0.4);
}

.lightbox {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.92);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 200;
}

.lightbox-img {
  max-width: 90vw;
  max-height: 90vh;
  object-fit: contain;
  border-radius: 0.5rem;
}

.lightbox-close {
  position: absolute;
  top: 1.5rem;
  right: 1.5rem;
  background: none;
  border: none;
  color: white;
  font-size: 2rem;
  cursor: pointer;
}

.lightbox-prev,
.lightbox-next {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  background: rgba(255, 255, 255, 0.1);
  border: none;
  color: white;
  font-size: 2rem;
  width: 3rem;
  height: 3rem;
  border-radius: 50%;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.2s ease;
}

.lightbox-prev { left: 1.5rem; }
.lightbox-next { right: 1.5rem; }

.lightbox-prev:hover,
.lightbox-next:hover {
  background: rgba(255, 255, 255, 0.2);
}
</style>

// src/components/common/ShowcaseModal.tsx
import { useState } from 'react';
import type { EventItem, GroupRef, ShowcaseItem } from '../../types/content';
import styles from './ShowcaseModal.module.css';

interface Props {
  showcase: ShowcaseItem | null;
  events: EventItem[];
  groups: GroupRef[];
  onClose: () => void;
}

type ViewMode = 'showcase' | 'announcement';

// 原本是 watch(() => props.showcase) 重設 viewMode 與 lightboxIndex；
// 用 key 讓內容元件在每次開啟時重新掛載，state 就自然回到初始值
export default function ShowcaseModal({ showcase, events, groups, onClose }: Props) {
  if (!showcase) return null;
  return (
    <ShowcaseModalContent key={showcase.id} showcase={showcase} events={events} groups={groups} onClose={onClose} />
  );
}

function ShowcaseModalContent({
  showcase,
  events,
  groups,
  onClose,
}: Props & { showcase: ShowcaseItem }) {
  const [viewMode, setViewMode] = useState<ViewMode>('showcase');
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null);

  const relatedEvent = (showcase.related_event && events.find((e) => e.id === showcase.related_event)) || null;

  const groupName = (slug: string) => {
    const g = groups.find((g) => g.slug === slug);
    return g ? g.name : slug;
  };

  const gallery = showcase.gallery ?? [];

  const lightboxPrev = () => {
    if (lightboxIndex === null || !showcase.gallery) return;
    setLightboxIndex((lightboxIndex - 1 + showcase.gallery.length) % showcase.gallery.length);
  };

  const lightboxNext = () => {
    if (lightboxIndex === null || !showcase.gallery) return;
    setLightboxIndex((lightboxIndex + 1) % showcase.gallery.length);
  };

  return (
    <div
      className={styles['modal-overlay']}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className={styles.modal}>
        <button className={styles['modal-close']} onClick={onClose}>
          ×
        </button>

        {relatedEvent && (
          <div className={styles['view-toggle']}>
            <button
              className={`${styles['toggle-btn']}${viewMode === 'showcase' ? ` ${styles.active}` : ''}`}
              onClick={() => setViewMode('showcase')}
            >
              活動回顧
            </button>
            <button
              className={`${styles['toggle-btn']}${viewMode === 'announcement' ? ` ${styles.active}` : ''}`}
              onClick={() => setViewMode('announcement')}
            >
              活動公告
            </button>
          </div>
        )}

        {viewMode === 'showcase' ? (
          <div>
            <div className={styles['modal-tags']}>
              <span className={`${styles.tag} ${styles['tag-group']}`}>{groupName(showcase.group)}</span>
              {showcase.tags?.map((tag) => (
                <span key={tag} className={styles.tag}>
                  {tag}
                </span>
              ))}
            </div>
            <h2 className={styles['modal-title']}>{showcase.title}</h2>
            <div className={styles['modal-meta']}>
              <span>{`📅 ${showcase.date}`}</span>
            </div>

            {showcase.cover_image && (
              <img src={showcase.cover_image} className={styles['cover-image']} alt={showcase.title} />
            )}

            <p className={styles['modal-description']}>{showcase.description}</p>

            {gallery.length > 0 && (
              <div className={styles['gallery-grid']}>
                {gallery.map((img, i) => (
                  <img key={i} src={img} className={styles['gallery-image']} onClick={() => setLightboxIndex(i)} />
                ))}
              </div>
            )}

            {showcase.links && showcase.links.length > 0 && (
              <div className={styles['modal-links']}>
                {showcase.links.map((link) => (
                  <a key={link.label} href={link.url} target="_blank" className={styles['modal-link-item']}>
                    {`🔗 ${link.label}`}
                  </a>
                ))}
              </div>
            )}
          </div>
        ) : (
          relatedEvent && (
            <div>
              <div className={styles['modal-tags']}>
                <span className={styles.tag}>{relatedEvent.type}</span>
                <span className={`${styles.tag} ${styles['tag-group']}`}>{groupName(relatedEvent.group)}</span>
              </div>
              <h2 className={styles['modal-title']}>{relatedEvent.title}</h2>
              <div className={styles['modal-meta']}>
                <span>{`📅 ${relatedEvent.date}`}</span>
                {relatedEvent.location && <span>{`📍 ${relatedEvent.location}`}</span>}
              </div>

              {relatedEvent.content && <p className={styles['modal-description']}>{relatedEvent.content}</p>}

              {relatedEvent.links && relatedEvent.links.length > 0 && (
                <div className={styles['modal-links']}>
                  {relatedEvent.links.map((link) => (
                    <a key={link.label} href={link.url} target="_blank" className={styles['modal-link-item']}>
                      {`🔗 ${link.label}`}
                    </a>
                  ))}
                </div>
              )}

              {relatedEvent.registration && (
                <a href={relatedEvent.registration} target="_blank" className={styles['modal-register-btn']}>
                  立即報名 →
                </a>
              )}
            </div>
          )
        )}
      </div>

      {lightboxIndex !== null && (
        <div className={styles.lightbox} onClick={() => setLightboxIndex(null)}>
          <button
            className={styles['lightbox-close']}
            onClick={(e) => {
              e.stopPropagation();
              setLightboxIndex(null);
            }}
          >
            ×
          </button>
          <button
            className={styles['lightbox-prev']}
            onClick={(e) => {
              e.stopPropagation();
              lightboxPrev();
            }}
          >
            ‹
          </button>
          <img src={gallery[lightboxIndex]} className={styles['lightbox-img']} onClick={(e) => e.stopPropagation()} />
          <button
            className={styles['lightbox-next']}
            onClick={(e) => {
              e.stopPropagation();
              lightboxNext();
            }}
          >
            ›
          </button>
        </div>
      )}
    </div>
  );
}
